// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/log10-io/log10go/models/components"
)

type CreateFeedbackTaskResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Task *components.Task
}

func (o *CreateFeedbackTaskResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateFeedbackTaskResponse) GetTask() *components.Task {
	if o == nil {
		return nil
	}
	return o.Task
}
