// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/log10-io/log10go/models/components"
)

type CreateGlobals struct {
	XLog10Organization *string `header:"style=simple,explode=false,name=X-Log10-Organization"`
}

func (o *CreateGlobals) GetXLog10Organization() *string {
	if o == nil {
		return nil
	}
	return o.XLog10Organization
}

type CreateRequest struct {
	XLog10Organization *string               `header:"style=simple,explode=false,name=X-Log10-Organization"`
	Completion         components.Completion `request:"mediaType=application/json"`
}

func (o *CreateRequest) GetXLog10Organization() *string {
	if o == nil {
		return nil
	}
	return o.XLog10Organization
}

func (o *CreateRequest) GetCompletion() components.Completion {
	if o == nil {
		return components.Completion{}
	}
	return o.Completion
}

type CreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	Any any
	// Created
	Completion *components.Completion
}

func (o *CreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}

func (o *CreateResponse) GetCompletion() *components.Completion {
	if o == nil {
		return nil
	}
	return o.Completion
}
