// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/log10-io/log10go/models/components"
)

type CreateSessionGlobals struct {
	XLog10Organization *string `header:"style=simple,explode=false,name=X-Log10-Organization"`
}

func (o *CreateSessionGlobals) GetXLog10Organization() *string {
	if o == nil {
		return nil
	}
	return o.XLog10Organization
}

type CreateSessionRequest struct {
	XLog10Organization *string `header:"style=simple,explode=false,name=X-Log10-Organization"`
}

func (o *CreateSessionRequest) GetXLog10Organization() *string {
	if o == nil {
		return nil
	}
	return o.XLog10Organization
}

// CreateSessionResponseBody - Created
type CreateSessionResponseBody struct {
	Session *components.Session `json:"session,omitempty"`
}

func (o *CreateSessionResponseBody) GetSession() *components.Session {
	if o == nil {
		return nil
	}
	return o.Session
}

type CreateSessionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	Object *CreateSessionResponseBody
}

func (o *CreateSessionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateSessionResponse) GetObject() *CreateSessionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
