// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/log10-io/log10go/models/components"
)

type GetFeedbackTaskRequest struct {
	// The task id to fetch.
	TaskID string `pathParam:"style=simple,explode=false,name=taskId"`
}

func (o *GetFeedbackTaskRequest) GetTaskID() string {
	if o == nil {
		return ""
	}
	return o.TaskID
}

type GetFeedbackTaskResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Task *components.Task
}

func (o *GetFeedbackTaskResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetFeedbackTaskResponse) GetTask() *components.Task {
	if o == nil {
		return nil
	}
	return o.Task
}
