// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/log10-io/log10go/models/components"
)

type ListGlobals struct {
	XLog10Organization *string `header:"style=simple,explode=false,name=X-Log10-Organization"`
}

func (o *ListGlobals) GetXLog10Organization() *string {
	if o == nil {
		return nil
	}
	return o.XLog10Organization
}

type ListRequestBody struct {
	// The offset to start fetching feedback from.
	Offset *int64 `json:"offset,omitempty"`
	// The number of feedback to fetch.
	Limit *int64 `json:"limit,omitempty"`
	// The completion id to fetch feedback for.
	CompletionID *string `json:"completion_id,omitempty"`
	// The task id to fetch feedback for.
	TaskID *string `json:"task_id,omitempty"`
}

func (o *ListRequestBody) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *ListRequestBody) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListRequestBody) GetCompletionID() *string {
	if o == nil {
		return nil
	}
	return o.CompletionID
}

func (o *ListRequestBody) GetTaskID() *string {
	if o == nil {
		return nil
	}
	return o.TaskID
}

type ListRequest struct {
	XLog10Organization *string          `header:"style=simple,explode=false,name=X-Log10-Organization"`
	RequestBody        *ListRequestBody `request:"mediaType=application/json"`
}

func (o *ListRequest) GetXLog10Organization() *string {
	if o == nil {
		return nil
	}
	return o.XLog10Organization
}

func (o *ListRequest) GetRequestBody() *ListRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

// ListResponseBody - OK
type ListResponseBody struct {
	Feedback []components.Feedback `json:"feedback,omitempty"`
}

func (o *ListResponseBody) GetFeedback() []components.Feedback {
	if o == nil {
		return nil
	}
	return o.Feedback
}

type ListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *ListResponseBody
}

func (o *ListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListResponse) GetObject() *ListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
