// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ChatCompletionStreamOptions - Options for streaming response. Only set this when you set `stream: true`.
type ChatCompletionStreamOptions struct {
	// If set, an additional chunk will be streamed before the `data: [DONE]` message. The `usage` field on this chunk shows the token usage statistics for the entire request, and the `choices` field will always be an empty array. All other chunks will also include a `usage` field, but with a null value.
	//
	IncludeUsage *bool `json:"include_usage,omitempty"`
}

func (o *ChatCompletionStreamOptions) GetIncludeUsage() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeUsage
}
