// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ChatCompletionFunctionCallOption - Specifying a particular function via `{"name": "my_function"}` forces the model to call that function.
type ChatCompletionFunctionCallOption struct {
	// The name of the function to call.
	Name string `json:"name"`
}

func (o *ChatCompletionFunctionCallOption) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
