// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// JSONValues - The values of the feedback. Must be valid JSON according to the task schema.
type JSONValues struct {
}

type Feedback struct {
	// The unique identifier for this feedback.
	ID *string `json:"id,omitempty"`
	// The epoch this schema was created.
	CreatedAtMs *float64 `json:"created_at_ms,omitempty"`
	// The unique identifier for the task associated with this feedback.
	TaskID string `json:"task_id"`
	// The values of the feedback. Must be valid JSON according to the task schema.
	JSONValues JSONValues `json:"json_values"`
	// The matched completion ids associated with this feedback.
	MatchedCompletionIds []string `json:"matched_completion_ids"`
	// The comment associated with this feedback.
	Comment            string  `json:"comment"`
	CompletionsSummary *string `json:"completions_summary,omitempty"`
}

func (o *Feedback) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Feedback) GetCreatedAtMs() *float64 {
	if o == nil {
		return nil
	}
	return o.CreatedAtMs
}

func (o *Feedback) GetTaskID() string {
	if o == nil {
		return ""
	}
	return o.TaskID
}

func (o *Feedback) GetJSONValues() JSONValues {
	if o == nil {
		return JSONValues{}
	}
	return o.JSONValues
}

func (o *Feedback) GetMatchedCompletionIds() []string {
	if o == nil {
		return []string{}
	}
	return o.MatchedCompletionIds
}

func (o *Feedback) GetComment() string {
	if o == nil {
		return ""
	}
	return o.Comment
}

func (o *Feedback) GetCompletionsSummary() *string {
	if o == nil {
		return nil
	}
	return o.CompletionsSummary
}
