// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Security struct {
	Log10Token *string `security:"scheme,type=apiKey,subtype=header,name=X-Log10-Token"`
}

func (o *Security) GetLog10Token() *string {
	if o == nil {
		return nil
	}
	return o.Log10Token
}
